# Generated by Django 4.0.2 on 2022-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
