# Generated by Django 4.0.2 on 2022-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profiles_id_alter_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
