# Generated by Django 4.0.2 on 2022-05-03 15:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=6)),
            ],
        ),
    ]
