# Generated by Django 4.0.2 on 2022-05-26 11:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hi',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
