# Generated by Django 4.0.2 on 2022-03-10 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=700, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pledge/')),
                ('raw_certificate', models.ImageField(upload_to='certificate/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pledge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='usercert/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pledge_data', to='pledge.pledge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_register_pledge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=700, null=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pledge/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_data', to='pledge.pledge')),
            ],
        ),
    ]
