# Generated by Django 4.0.2 on 2022-03-10 12:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpledge',
            name='uid',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12),
        ),
    ]
