# Generated by Django 4.0.2 on 2022-02-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='support',
        ),
        migrations.AddField(
            model_name='support',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_conversation', to='support.ticket'),
            preserve_default=False,
        ),
    ]
