# Generated by Django 4.0.2 on 2022-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_curriculum_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='attachment_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text')], default='image', max_length=300),
        ),
    ]
