# Generated by Django 4.0.2 on 2022-05-20 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_usertask_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='content_hn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title_hn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
