# Generated by Django 4.0.2 on 2022-05-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_curriculum_content_en_curriculum_content_hn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='content_hn',
            new_name='content_hi',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='title_hn',
            new_name='title_hi',
        ),
    ]
