# Generated by Django 4.0.2 on 2022-05-26 12:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacontent',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacontent',
            name='content_hi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metacontent',
            name='title_en',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metacontent',
            name='title_hi',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='content_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title_en',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title_hi',
            field=models.CharField(max_length=400, null=True, unique=True),
        ),
    ]
