# Generated by Django 4.0.2 on 2022-05-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_metacontent_content_en_metacontent_content_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='content_hi',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='title_hi',
        ),
    ]
