# Generated by Django 4.0.2 on 2022-05-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_en',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_hi',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
